config/routes.rb
Rails.application.routes.draw do
  resources :clients
  root 'clients#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
	def self.search(query)
		where("nom LIKE ?", "%#{query}%")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    if params[:search]
      @clients = Client.search(params[:search]).order("created_at DESC")
    else
      @clients = Client.order("created_at DESC")
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Votre client a bien été ajouté.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Votre client a bien été modifié.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Votre client a bien été supprimé.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:nom, :prenom, :numero, :adresse, :codepostal, :ville, :note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
    <div class="field">
      <%= f.label :nom %><br>
      <%= f.text_field :nom, class: "form-control text-center" %>
    </div>
    <div class="field">
      <%= f.label :prenom %><br>
      <%= f.text_field :prenom, class: "form-control text-center" %>
    </div>
    <div class="field">
      <%= f.label :numero %><br>
      <%= f.text_field :numero, class: "form-control text-center" %>
    </div>
    <div class="field">
      <%= f.label :adresse %><br>
      <%= f.text_field :adresse, class: "form-control text-center" %>
    </div>
    <div class="field">
      <%= f.label :codepostal %><br>
      <%= f.text_field :codepostal, class: "form-control text-center" %>
    </div>
    <div class="field">
      <%= f.label :ville %><br>
      <%= f.text_field :ville, class: "form-control text-center" %>
    </div>
    <div class="field form-group">
      <%= f.label :note %><br>
      <%= f.text_area :note, class: "form-control text-center" %>
    </div>
    <div class="actions">
      <%= f.submit ('Soumettre'), class: "btn btn-primary" %>
    </div>

<% end %>

app/views/clients/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2 text-center">

			<h1>Modifier Client :</h1>

				<%= render 'form' %>

		</div> <!-- col-md-8.end -->
	</div> <!-- row.end -->
</div> <!-- container.end -->

app/views/clients/index.html.erb
<div class="alert-danger text-center" role="alert">
  <p id="notice"><%= notice %></p>
</div>

<div class="container">
  <div class="row">
    <div class="page-header col-md-4 col-md-offset-4 text-center">
      <h1><strong>Fichier Clients :</strong></h1>

          <%= form_tag(clients_path, method: :get) do %>
          <%= text_field_tag (:search) %>
          <%= submit_tag ("Rechercher"), class: "btn btn-primary btn-sm" %>
          <% end %>

    </div>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-hover">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Prenom</th>
      <th>Numero</th>
      <th>Adresse</th>
      <th>Codepostal</th>
      <th>Ville</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.nom %></td>
        <td><%= client.prenom %></td>
        <td><%= client.numero %></td>
        <td><%= client.adresse %></td>
        <td><%= client.codepostal %></td>
        <td><%= client.ville %></td>
        <td><%= link_to 'Afficher', client, class: "btn btn-info btn-sm" %></td>
        <td><%= link_to 'Modifier', edit_client_path(client), class: "btn btn-warning btn-sm"%></td>
        <td><%= link_to 'Supprimer', client, method: :delete, data: { confirm: 'Etes vous sur ?' }, class: "btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
</div>

app/views/clients/new.html.erb
<div class="container text-center">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">

			<h1>Ajouter Client :</h1>

			<%= render 'form' %>

		</div> <!-- col-md-8.end -->
	</div> <!-- row.end -->
</div> <!-- container.end -->

app/views/clients/show.html.erb
<div class="alert-success text-center" role="alert">
  <p id="notice"><%= notice %></p>
</div>


<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <ul class="list-group">
        <li class="list-group-item active  text-center"><strong class="navbar-left">Nom:</strong><%= @client.nom %></li>
        <li class="list-group-item text-center"><strong class="navbar-left">Prenom:</strong><%= @client.prenom %></li>
        <li class="list-group-item text-center"><strong class="navbar-left">Numero:</strong><%= @client.numero %></li>
        <li class="list-group-item text-center"><strong class="navbar-left">Adresse:</strong><%= @client.adresse %></li>
        <li class="list-group-item text-center"><strong class="navbar-left">Codepostal:</strong><%= @client.codepostal %></li>
        <li class="list-group-item text-center"><strong class="navbar-left">Ville:</strong><%= @client.ville %></li>
        <li class="list-group-item text-center"><strong class="navbar-left">Note:</strong><%= @client.note %></li>
      </ul>

      <div class="text-center">
        <%= link_to 'Modifier', edit_client_path(@client), class: "btn btn-warning" %> |
        <%= link_to 'Retour', clients_path, class: "btn btn-warning" %>
      </div>

    </div> <!-- col-md-6.end -->
  </div> <!-- row.end -->
</div> <!-- container.end -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fichier Client Pizza Massilia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-inverse navbar-static-top">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <a class="navbar-brand" href="http://pizza-massilia.fr/">
	        <%= image_tag("logo.png") %>
	      </a>
	      <ul class="nav navbar-nav">
	      <li class="active"><%= link_to 'Accueil', clients_path%></li>
	      <li><%= link_to 'Nouveau client', new_client_path %></li>
	      </ul>
	    </div>
	  </div>
	</nav>

<%= yield %>

</body>
</html>